version: '3.8'

services:
  alertmanager:
    image: prom/alertmanager:latest
    container_name: sicherheitsdienst-alertmanager
    ports:
      - '9093:9093'
    environment:
      ALERTMANAGER_SLACK_WEBHOOK: ${ALERTMANAGER_SLACK_WEBHOOK}
      ALERTMANAGER_SLACK_CHANNEL: ${ALERTMANAGER_SLACK_CHANNEL}
      ALERTMANAGER_WEBHOOK_URL: ${ALERTMANAGER_WEBHOOK_URL}
      ALERTMANAGER_WEBHOOK_BEARER: ${ALERTMANAGER_WEBHOOK_BEARER}
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml:ro
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--web.listen-address=:9093'
    networks: [ 'obs' ]

  prometheus:
    image: prom/prometheus:latest
    container_name: sicherheitsdienst-prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alerts/alerts.yml:/etc/prometheus/alerts.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    depends_on:
      - alertmanager
    networks: [ 'obs' ]

  grafana:
    image: grafana/grafana:latest
    container_name: sicherheitsdienst-grafana
    ports:
      - '3300:3000'
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks: [ 'obs' ]
    depends_on:
      - prometheus

networks:
  obs:
    driver: bridge
